#JOC064 BulkRNA seq analysis adapted from JOC047 BulkRNA seq analysis
#Repeat analysis of JOC047 isolated and FACS sorted DCs from livers of Pdl1cymt ant WT mice after 22weeks on HFHC diet
#07242026


#####Quality check raw files#####

#fastQc to check quality of reads, base calls, GC content, adapter contamination... etc
##code from class notes was updated to this code with chatgpt because previous package installed used to have fastqc as a function but now it doesnt. So now I have to update code to have correct executable fastqc.
fq.files <- list.files(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles",
  pattern = "\\.(fastq|fq)(\\.gz)?$",
  full.names = TRUE
)

dir.create(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
  showWarnings = FALSE
)

system2(
  "/opt/homebrew/bin/fastqc",
  args = c(
    "-t", "1",
    "-o", "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
    fq.files
  )
)

#MultiQC to merge files and compare statistics across samples.

dir.create(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/MultiQCOutput",
  showWarnings = FALSE
)

system2(
  "/Users/jessica/.local/bin/multiqc",
  args = c(
    "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
    "--outdir",
    "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/MultiQCOutput"
  )
)


####Trimming adapter sequences####


#cutadapt to trim adapter sequences from class notes. But I actually used the code below generated by chatgpt using class notes for guidance.
##code below updated 07262026 to run faster and analyze simultaneously all samples.

input_dir <- "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles"
output_dir <- file.path(input_dir, "Trimmed")

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

r1_files <- list.files(
  input_dir,
  pattern = "_R1_001\\.fastq\\.gz$",
  full.names = TRUE
)

for (r1 in r1_files) {
  
  r2 <- sub("_R1_001\\.fastq\\.gz$", "_R2_001.fastq.gz", r1)
  
  sample <- sub("_R1_001\\.fastq\\.gz$", "", basename(r1))
  
  out_r1 <- file.path(output_dir, paste0(sample, "_R1_trimmed.fastq.gz"))
  out_r2 <- file.path(output_dir, paste0(sample, "_R2_trimmed.fastq.gz"))
  
  message("========================================")
  message("Processing sample: ", sample)
  message("========================================")
  
  system2(
    "/Users/jessica/miniconda3/envs/cutadapt-env/bin/cutadapt",
    args = c(
      "-j", "8",
      "-a", "AGATCGGAAGAG",
      "-A", "AGATCGGAAGAG",
      "-q", "20",
      "--minimum-length", "10",
      "--pair-filter=any",
      "-o", out_r1,
      "-p", out_r2,
      r1,
      r2
    )
  )
}

message("All samples completed.")


#####Quality check of Trimmed files######
##...##07262026##

fq.files <- list.files(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles",
  pattern = "\\.(fastq|fq)(\\.gz)?$",
  full.names = TRUE
)

dir.create(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
  showWarnings = FALSE
)

system2(
  "/opt/homebrew/bin/fastqc",
  args = c(
    "-t", "1",
    "-o", "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
    fq.files
  )
)

#MultiQC to merge files and compare statistics across samples.

dir.create(
  "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/MultiQCOutput",
  showWarnings = FALSE
)

system2(
  "/Users/jessica/.local/bin/multiqc",
  args = c(
    "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/FastqOutput",
    "--outdir",
    "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/MultiQCOutput"
  )
)













##Fastqc of newly trimmed files. code from chatgpt using class notes as guidance.
# Paths
trimmed_dir <- "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/Trimmed/"
fastqc_output <- "/Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/trimmed_FastqcOutput/"
fastqc_bin <- "/opt/homebrew/bin/fastqc"

# Create output folder if needed
dir.create(fastqc_output, showWarnings = FALSE)

# List FASTQ files
fastq_files <- list.files(trimmed_dir, pattern = "\\.fastq\\.gz$", full.names = TRUE)

# Run FastQC
for (fq in fastq_files) {
  cmd <- sprintf("'%s' -o '%s' '%s'", fastqc_bin, fastqc_output, fq)
  message("Running FastQC on: ", basename(fq))
  system(cmd)
}

##Multiqc to merge new fastqc output of trimmed files. code from class notes and chatGPT
system("/Users/jessica/.local/bin/multiqc /Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/ --outdir /Volumes/JOlivas#1/JOC064_Bulkseq_fastafiles/trimmed_MultiqcOutput/")



#######Reference genome mus_musculusGRCm39_112#######

#Reference genome downloaded with script from chatGPT
# Set Ensembl release and organism
#   ENSEMBL_RELEASE=112
#   SPECIES=mus_musculus
#   GENOME=GRCm39


library(Rsubread)

buildindex(
  basename = "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/mouse_reference/mouse_reference/GRCm39_rsubread_index",
  reference = "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/mouse_reference/mouse_reference/Mus_musculus.GRCm39.dna.primary_assembly.fa",
  gappedIndex = TRUE,
  memory = 8000
)


#alignnment of trimmed fasta files to reference genome
#code from class and modified with chatGPT
library(Rsubread)

# Define paths
base_path <- "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_files"
index_path <- "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/mouse_reference/mouse_reference/GRCm39_rsubread_index"
gtf_path <- "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/mouse_reference/mouse_reference/Mus_musculus.GRCm39.112.gtf"

# Get all R1 fastq files
r1_files <- list.files(base_path, pattern = "_R1_trimmed.fastq.gz$", full.names = TRUE)

# Derive sample names
sample_names <- sub("_R1_trimmed.fastq.gz$", "", basename(r1_files))

# Align each sample
for (sample in sample_names) {
  cat("🔄 Aligning:", sample, "\n")
  
  read1 <- file.path(base_path, paste0(sample, "_R1_trimmed.fastq.gz"))
  read2 <- file.path(base_path, paste0(sample, "_R2_trimmed.fastq.gz"))
  output_bam <- file.path(base_path, paste0(sample, "_aligned_sorted.bam"))
  
  align(
    index = index_path,
    readfile1 = read1,
    readfile2 = read2,
    output_file = output_bam,
    sortReadsByCoordinates = TRUE,
    type = "rna",
    useAnnotation = TRUE,
    annot.ext = gtf_path,
    isGTF = TRUE,
    nthreads = 6,
    GTF.featureType = "exon",
    GTF.attrType = "gene_id",
  )
  
  cat("✅ Finished:", sample, "\n\n")
}



##Generating gene-level counts using 'feature counts'
##code from ChatGPT. 


library(Rsubread)

# Set paths
bam_dir <- "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_files"
gtf_file <- "/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_FastqcOutput/mouse_reference/mouse_reference/Mus_musculus.GRCm39.112.gtf"

# Find all aligned BAM files
bam_files <- list.files(bam_dir, pattern = "_aligned_sorted.bam$", full.names = TRUE)

# Run featureCounts
fc <- featureCounts(
  files = bam_files,
  annot.ext = gtf_file,
  isGTFAnnotationFile = TRUE,
  GTF.featureType = "exon",
  GTF.attrType = "gene_name",
  isPairedEnd = TRUE,
  nthreads = 6
)

# Save counts to file
write.csv(fc$counts, file = file.path(bam_dir, "gene_counts_matrix.csv"))



# Alpine HPC workflow -----------------------------------------------------
##Code written using chatGPT. Substituted HPC directories with random names (to protect actual directories within a shared resource) in chatGPT and corrected the code pasted below to reflect working code.


####!/bin/bash####

# Local source directory on the external hard drive
SOURCE_DIR="/Volumes/JOlivas#1/JOC047_BulkRNAseq_fastq_files/trimmed_files/"

# Remote login info
HPC_USER="jolivascorral"
HPC_HOST="login.xsede.org"

# Remote destination path - quotes used to handle special characters like @
REMOTE_DIR="/scratch/alpine/jolivascorral\@xsede.org"

# Run rsync to copy only *trimmed.fastq.gz files
rsync -avz --progress \
--include="*/" \
--include="*trimmed.fastq.gz" \
--exclude="*" \
"$SOURCE_DIR" "$HPC_USER@$HPC_HOST:$REMOTE_DIR"



##Fasta files were transferred to HPC alpine via GLobus connect. On HPC, I ran STAR align on samples to align with mouse reference genome Grcmm39.112(downloaded from ensembl). This generated bam file and gene count files. Picard tools CollecRNAseq metrics was then ran by using .bed and .dict and .refFlat files. I used GTF reference file to generate refFLat via conda environment of Picard. Also used samtools to generate .bed and .dict files via conda enviornment. Picard rna_metrics files and all files generated on HPC were transferred back to onedrive files. further multiqc analysis and downstream gene count analysis is preformed via R/Rstudio. 


input_dir <- path.expand("~/OneDrive - The University of Colorado Denver/Tamburini Lab/experiments/project_4_HFHC/JOC047 - 22wkHFHC seq/trimmed_fasta_files/Picard_metrics")
output_dir <- "multiqc_output"

# Create output folder if it doesn't exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

# Use shQuote to handle spaces in the path
cmd <- paste("/Users/jessica/.local/bin/multiqc", shQuote(input_dir), "-o", shQuote(output_dir))

# Run the command
system(cmd)


browseURL(file.path(output_dir, "multiqc_report.html"))



#merging of data into table format
#featureCounts with paired end analysis of reverse strqand (SMART kit compatible -according to chatgpt)
#running in bash
featureCounts -T 6 \
-p \
-s 2 \
-a ~/OneDrive\ -\ The\ University\ of\ Colorado\ Denver/Tamburini\ Lab/experiments/project_4_HFHC/JOC047\ -\ 22wkHFHC\ seq/trimmed_fasta_files/reference_genomes/Mus_musculus.GRCm39.112.gtf \
-o ~/OneDrive\ -\ The\ University\ of\ Colorado\ Denver/Tamburini\ Lab/experiments/project_4_HFHC/JOC047\ -\ 22wkHFHC\ seq/trimmed_fasta_files/results/counts_JOC047.txt \
~/OneDrive\ -\ The\ University\ of\ Colorado\ Denver/Tamburini\ Lab/experiments/project_4_HFHC/JOC047\ -\ 22wkHFHC\ seq/trimmed_fasta_files/STARalign_output/*Aligned.sortedByCoord.out.bam

##the following code is run on R
#Import counts into R and prepare DESeq2 input. - code by chatGPT

# Load libraries
library(DESeq2)
library(pheatmap)
library(ggplot2)
library(grid)

# Set working directory (optional)
setwd("~/OneDrive - The University of Colorado Denver/Tamburini Lab/experiments/project_4_HFHC/JOC047 - 22wkHFHC seq/trimmed_fasta_files/results")

# Read the count matrix
counts <- read.delim("counts_JOC047.txt", comment.char = "#", row.names = 1)

# Remove extra columns (Chr, Start, End, Strand, Length)
counts <- counts[,6:ncol(counts)]

# Confirm structure
head(counts)

#Create sample metadata (colData)
# Check sample names
colnames(counts)

# Create condition vector
# Adjust sample names to match those in your counts file exactly
sample_names <- colnames(counts)
condition <- c(rep("WT", 5), rep("CyMt", 5))  # Update if needed

# Create colData (sample metadata)
coldata <- data.frame(row.names = sample_names, condition = factor(condition))
coldata


##Create DESeq2 dataset
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = coldata,
                              design = ~ condition)

#filtering to remove genes with very low counts . <10/gene across all samples
dds <- dds[ rowSums(counts(dds)) > 10, ]

#Run DESeq2
dds <- DESeq(dds)
res <- results(dds)

#Explore results
# View top differentially expressed genes
head(res[order(res$padj), ], 10)

# Save results to CSV
write.csv(as.data.frame(res), file = "deseq2_results.csv")

#Visualization PCA plot and heatmap of top 50 genes
vsd <- vst(dds, blind = FALSE)
plotPCA(vsd, intgroup = "condition")


top_genes <- head(order(rowMeans(counts(dds, normalized=TRUE)), decreasing = TRUE), 50)
pheatmap(assay(vsd)[top_genes, ], cluster_rows=TRUE, cluster_cols=TRUE, show_rownames=FALSE)


#plotting DEGs by genotypes
# Ensure required libraries are loaded

# 1. Order DESeq2 results by adjusted p-value (padj)
resOrdered <- res[order(res$padj), ]

# 2. Filter out genes with NA padj values
resOrdered <- resOrdered[!is.na(resOrdered$padj), ]

# 3. Select top 50 DEGs (most statistically significant)
top_degs <- rownames(resOrdered)[1:50]

# 4. Create sample group annotation
annotation_col <- data.frame(
  Condition = colData(dds)$condition
)
rownames(annotation_col) <- colnames(dds)

# 5. Plot heatmap using variance-stabilized transformed data
pheatmap(assay(vsd)[top_degs, ],
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         show_rownames = TRUE,
         annotation_col = annotation_col,
         fontsize_row = 6,
         scale = "row",  # scale each gene across samples for better contrast
         main = "Top 50 Differentially Expressed Genes")

#CODE from CHATGPT to display gene names instead of gene IDs on heatmaps
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("biomaRt")

# Use Ensembl BioMart for mouse
ensembl <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")

# Get mapping: Ensembl gene ID → external gene name
gene_map <- getBM(
  attributes = c("ensembl_gene_id", "external_gene_name"),
  filters = "ensembl_gene_id",
  values = rownames(dds),
  mart = ensembl
)

 #Replace Ensembl IDs with gene names in your top DEGs
# Merge top DEGs with gene names
top_degs_df <- data.frame(gene_id = top_degs)
top_degs_named <- merge(top_degs_df, gene_map, by.x = "gene_id", by.y = "ensembl_gene_id")

# Remove rows without gene name
top_degs_named <- top_degs_named[!top_degs_named$external_gene_name == "", ]

# Extract gene expression for those top DEGs
mat <- assay(vsd)[top_degs_named$gene_id, ]

# Replace rownames (Ensembl IDs) with gene names
rownames(mat) <- top_degs_named$external_gene_name


pdf("top_DEGs_named_heatmap.pdf", width = 10, height = 12)

# Draw heatmap WITHOUT main argument
p <- pheatmap(mat,
              cluster_rows = TRUE,
              cluster_cols = TRUE,
              show_rownames = TRUE,
              annotation_col = annotation_col,
              fontsize_row = 8,
              fontsize_col = 10,
              angle_col = 45,
              scale = "row",
              border_color = NA,
              cellwidth = 15,
              cellheight = 10)

# Add title above the heatmap using grid.text
grid.text("Top DEGs with Gene Names", y = unit(0.98, "npc"), gp = gpar(fontsize = 16, fontface = "bold"))

dev.off()

# Suppose your original sample names are like:
# "1_WT1_S8_L007_Aligned.sortedByCoord.out.bam"
# "6_CyMt1_S13_L007_Aligned.sortedByCoord.out.bam"
# etc.

# Get current column names
original_names <- colnames(mat)

# Extract short sample names using regex
# This example assumes the format is:
# [number]_[sampleID]_S[number]_L[number]_Aligned.sortedByCoord.out.bam

short_names <- sub(".*?_(WT\\d+|CyMt\\d+)_.*", "\\1", original_names)

# Assign the simplified names back to the matrix
colnames(mat) <- short_names

# Now plot with updated column names
library(pheatmap)
library(grid)

pdf("top_DEGs_named_heatmap_shortnames.pdf", width = 10, height = 12)

p <- pheatmap(mat,
              cluster_rows = TRUE,
              cluster_cols = TRUE,
              show_rownames = TRUE,
              annotation_col = annotation_col,
              fontsize_row = 8,
              fontsize_col = 10,
              angle_col = 45,
              scale = "row",
              border_color = NA,
              cellwidth = 15,
              cellheight = 10)

grid.text("Top DEGs with Gene Names", y = unit(0.98, "npc"), gp = gpar(fontsize = 16, fontface = "bold"))

dev.off()


# Step 1: Extract sample names from annotation_col rownames

# Your current annotation rownames (long file paths):
ann_rows <- rownames(annotation_col)

# Extract the sample name pattern like WT1 or CyMt5 from those paths
clean_names <- sub(".*_(WT\\d+|CyMt\\d+)_.*", "\\1", ann_rows)

# Step 2: Replace annotation rownames with these clean sample names
rownames(annotation_col) <- clean_names

# Step 3: Check if now the names match
all(rownames(annotation_col) == colnames(mat))
# This should print TRUE

# Now you can safely plot your heatmap
library(pheatmap)
# Define your desired sample order
desired_order <- c("WT1", "WT2", "WT3", "WT4", "WT5",
                   "CyMt1", "CyMt2", "CyMt3", "CyMt4", "CyMt5")

# Reorder your count matrix columns
mat_ordered <- mat[, desired_order]

# Reorder your annotation to match the same order
annotation_col_ordered <- annotation_col[desired_order, , drop = FALSE]

# Now plot with the ordered data and disable column clustering to keep order
# Open PDF with larger height for visibility
pdf("heatmap_top_DEGs_ordered.pdf", width = 12.5, height = 8.5)

# Create heatmap
p <- pheatmap(mat_ordered,
              cluster_rows = TRUE,
              cluster_cols = FALSE,
              show_rownames = TRUE,
              show_colnames = TRUE,              # <-- ensure sample names are shown
              annotation_col = annotation_col_ordered,
              fontsize_row = 8,
              fontsize_col = 12,                 # <-- increase column font size
              angle_col = 45,
              scale = "row",
              border_color = NA,
              cellwidth = 20,                    # <-- increase cell width
              cellheight = 12)                   # <-- increase cell height
print(p)
dev.off()

########################################
##generating volcano plot 
volcano_labeled <- ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = padj < 0.05 & abs(log2FoldChange) >= 1), alpha = 0.8, size = 1.5) +
  geom_text_repel(
    aes(label = label),
    size = 3,
    max.overlaps = 50,
    box.padding = 0.4,
    point.padding = 0.3,
    segment.color = "grey50",
    na.rm = TRUE
  ) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "grey")) +
  xlim(c(-6, 6)) +   # Fixed x-axis limits
  ylim(c(0, max(-log10(res_df$padj), na.rm = TRUE))) +  # y-axis from 0 to max
  theme_minimal() +
  labs(
    title = "Volcano Plot with Gene Names",
    x = "Log2 Fold Change (CyMt vs WT)",
    y = "-Log10 Adjusted p-value"
  ) +
  theme(
    legend.position = "none",
    plot.margin = unit(c(1, 1, 1, 1), "lines")
  )

# Save as PDF
ggsave("volcano_gene_names.pdf", volcano_labeled, width = 10, height = 8)


#############################
#START of GSEA analysis

# Install BiocManager if not already available
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

# Install required Bioconductor and CRAN packages
BiocManager::install(c(
  "clusterProfiler", 
  "org.Mm.eg.db", 
  "msigdbr", 
  "enrichplot"
))

# Install CRAN packages
install.packages(c("ggplot2", "dplyr"))



library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(dplyr)

# Ensure gene IDs are mapped to gene symbols
res_df <- res_df %>% 
  dplyr::filter(!is.na(padj)) %>%
  dplyr::arrange(desc(log2FoldChange)) 

# Create a named vector: gene log2FCs named by gene symbol
gene_list <- res_df$log2FoldChange
names(gene_list) <- res_df$external_gene_name  # or whatever gene name column you have

# Remove duplicates and NAs
gene_list <- gene_list[!duplicated(names(gene_list)) & !is.na(names(gene_list))]
gene_list <- sort(gene_list, decreasing = TRUE)

gene_list_df <- data.frame(
  gene = names(gene_list),
  log2FoldChange = gene_list
)

# View the first few entries
head(gene_list_df)

# Optional: Save to CSV
write.csv(gene_list_df, "ranked_gene_list.csv", row.names = FALSE)


####I think WT5 and CyMt5 labels were swapped.#####
library(DESeq2)
library(ggplot2)

# PCA plot
vsd <- vst(dds, blind = TRUE)
plotPCA(vsd, intgroup = "condition") + ggtitle("PCA of Samples")

# Check current labels
colData(dds)$condition

# Create a corrected condition vector
corrected_condition <- colData(dds)$condition

# Swap WT5 ↔ CyMt5
corrected_condition[colnames(dds) == "WT5"] <- "CyMt"
corrected_condition[colnames(dds) == "CyMt5"] <- "WT"

# Assign it back to DESeq2 object
colData(dds)$condition <- factor(corrected_condition, levels = c("WT", "CyMt"))

#Rerun DESeq2 analysis
dds <- DESeq(dds)
res <- results(dds)

write.csv(as.data.frame(res), "DESeq2_results_corrected_labels.csv")

vsd <- vst(dds, blind = TRUE)
plotPCA(vsd, intgroup = "condition") + ggtitle("PCA with Corrected Sample Labels")

res_df <- as.data.frame(res)
res_df$gene <- rownames(res_df)
res_df$significance <- ifelse(res_df$padj < 0.05 & abs(res_df$log2FoldChange) > 1, "Significant", "Not Significant")
res_df$label <- ifelse(res_df$significance == "Significant", gene_names[rownames(res_df)], NA)  # replace with mapped names if available

library(ggplot2)
library(ggrepel)

ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj), color = significance)) +
  geom_point() +
  geom_text_repel(aes(label = label), size = 3, max.overlaps = 25) +
  scale_color_manual(values = c("grey", "red")) +
  theme_minimal() +
  labs(title = "Volcano Plot (Corrected Labels)", x = "Log2 Fold Change", y = "-Log10 adjusted p-value")

#Map ensembl gene IDs to gene symbols
library(AnnotationDbi)

# Ensure your DESeq2 results are loaded
gene_ids <- rownames(res_df)

# Create the mapping
gene_names <- mapIds(
  org.Mm.eg.db,
  keys = gene_ids,
  column = "SYMBOL",       # what we want
  keytype = "ENSEMBL",     # what we have
  multiVals = "first"      # return the first match if multiple
)


res_df$label <- ifelse(res_df$significance == "Significant", gene_names[rownames(res_df)], NA)


#Volcano plot
library(ggplot2)
library(ggrepel)

volcano_labeled <- ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj), color = significance)) +
  geom_point(alpha = 0.8, size = 1.5) +
  geom_text_repel(
    aes(label = label),
    size = 3,
    max.overlaps = 25,
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey60"
  ) +
  scale_color_manual(values = c("Not Significant" = "grey", "Significant" = "red")) +
  coord_cartesian(xlim = c(-6, 6)) +
  theme_minimal() +
  labs(title = "Volcano Plot: Labeled Significant Genes",
       x = "Log2 Fold Change (CyMt vs WT)",
       y = "-Log10 Adjusted p-value") +
  theme(legend.title = element_blank())

ggsave("volcano_genes_labeled.pdf", volcano_labeled, width = 10, height = 8)

#shortening colnames 
# Extract gene symbols from Ensembl IDs (assuming gene_names is a named vector: names=ensembl, values=symbol)
gene_symbols_top <- gene_names[rownames(vsd)]

# Get normalized counts and select top 50 genes by mean expression
normalized_counts <- counts(dds, normalized = TRUE)
top_genes <- head(order(rowMeans(normalized_counts), decreasing = TRUE), 50)

# Subset vsd assay for those top genes
mat <- assay(vsd)[top_genes, ]

# Replace rownames (Ensembl) with gene symbols
rownames(mat) <- gene_symbols_top[top_genes]

# Fix colnames (sample names)
colnames(mat) <- sub(".*STARalign_output\\.(\\d+_)?(WT\\d|CyMt\\d).*", "\\2", colnames(mat))

# Define desired order of samples (columns)
desired_order <- c("WT1", "WT2", "WT3", "WT4", "WT5", 
                   "CyMt1", "CyMt2", "CyMt3", "CyMt4", "CyMt5")

# Reorder columns
mat <- mat[, desired_order]

# Set up annotation for columns
annotation_col <- data.frame(Group = factor(gsub("[0-9]", "", colnames(mat))))
rownames(annotation_col) <- colnames(mat)

# Load pheatmap
library(pheatmap)

# Save heatmap to PDF
pdf("heatmap_top50_genes_named.pdf", width = 11, height = 8)
# Define colors for groups
annotation_colors <- list(
  Group = c(WT = "navy", CyMt = "red")
)

# Then add this argument inside your pheatmap call:

pheatmap(mat,
         cluster_rows = TRUE,
         cluster_cols = FALSE,
         show_rownames = TRUE,
         annotation_col = annotation_col,
         annotation_colors = annotation_colors,  # <--- Add this line
         fontsize_row = 8,
         fontsize_col = 10,
         angle_col = 45,
         scale = "row",
         border_color = NA,
         cellwidth = 18,
         cellheight = 10)

dev.off()








################################
#variance stabilized transformed DESeq2 dataset
# Generate VST-transformed matrix from DESeq2 object
vsd <- vst(dds)
vsd_mat <- assay(vsd)

###############################

# Shorten sample names (e.g., "WT1", "CyMt5")
colnames(vsd_mat) <- sub(".*STARalign_output\\.(\\d+_)?(WT\\d|CyMt\\d).*", "\\2", colnames(vsd_mat))

# Swap labels for WT5 and CyMt5 if they were switched
corrected_names <- colnames(vsd_mat)
corrected_names[corrected_names == "WT5"] <- "TEMP"
corrected_names[corrected_names == "CyMt5"] <- "WT5"
corrected_names[corrected_names == "TEMP"] <- "CyMt5"
colnames(vsd_mat) <- corrected_names
colnames(vsd) <- corrected_names  # Also update names in the DESeq2 object

# Update condition metadata (WT vs CyMt)
colData(dds)$condition <- factor(ifelse(grepl("WT", corrected_names), "WT", "CyMt"))

library(ggplot2)

# Run PCA
pca_data <- plotPCA(vsd, intgroup = "condition", returnData = TRUE)
percentVar <- round(100 * attr(pca_data, "percentVar"))

# Save PCA plot to PDF
pdf("PCA_plot_corrected.pdf", width = 8, height = 6)
ggplot(pca_data, aes(PC1, PC2, color = condition, label = name)) +
  geom_point(size = 3) +
  geom_text(vjust = -1.2, size = 3) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  scale_color_manual(values = c("WT" = "navy", "CyMt" = "red")) +
  theme_minimal()
dev.off()

#Select top 50 most expressed genes from normalized counts
normalized_counts <- counts(dds, normalized = TRUE)
# Get top 50 DEGs based on adjusted p-value
top_degs <- head(order(res$padj, decreasing = FALSE), 50)

# Use VST-transformed values for those genes
mat <- assay(vsd)[top_degs, ]

# Map gene symbols
gene_symbols_top <- gene_names[rownames(mat)]
rownames(mat) <- gene_symbols_top

# Reorder sample columns (use previously corrected names)
desired_order <- c("WT1", "WT2", "WT3", "WT4", "WT5", 
                   "CyMt1", "CyMt2", "CyMt3", "CyMt4", "CyMt5")
mat <- mat[, desired_order]

# Update annotation for plotting
annotation_col <- data.frame(Group = factor(gsub("[0-9]", "", colnames(mat)),
                                            levels = c("WT", "CyMt")))
rownames(annotation_col) <- colnames(mat)

# Plot heatmap
library(pheatmap)
pdf("heatmap_top50_DEGs_named_corrected.pdf", width = 11, height = 8.5)
pheatmap(mat,
         cluster_rows = TRUE,
         cluster_cols = FALSE,
         show_rownames = TRUE,
         annotation_col = annotation_col,
         annotation_colors = list(Group = c(WT = "navy", CyMt = "red")),
         fontsize_row = 8,
         fontsize_col = 10,
         angle_col = 45,
         scale = "row",
         border_color = NA,
         cellwidth = 18,
         cellheight = 10)
dev.off()
